### ISSUE TITLE
Doesn't use .Site.copyright?

### ISSUE THREAD

**Issue by fasiha** [gizak/nofancy#1]
`layouts/partials/footer.html` doesn't seem to include a check for `.Site.copyright`? I'm trying to fix this but having some trouble, otherwise I'd offer a pull request.

**Comment by gizak** [comment]
Hi fasiha! I just pushed a commit https://github.com/gizak/nofancy/commit/af158004eb513a3411fb1cddb3404187e9a3f2e5: If `copyright` is provided in the config file, it will override the default one, otherwise the default copyright will be used.
